### ISSUE TITLE
Please create TEAL Version 3 for collecting TEAL changes for future releases

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1633]
@jannotti and I were just talking about it would be useful for `go-algorand` to have a "TEAL version 3" in the consensus parameters and in the TEAL evaluator that is currently turned off and intended to be turned off until some later date, but that can be optionally enabled in development nodes (not TestNet or BetaNet) for testing Algorand dApps. A pattern like this would ensure that existing TEAL contract behavior doesn't change, but would facilitate developing more advanced TEAL programs, the Reach compiler, and the future Algorand layer-2 contracts.

There are many simple things that could be added and tested quickly if there were a structure like this in place:
- [ ] stateless args visible to other txns (#1533 / #1640 )
- [ ] swap (#1534 / #1640)
- [ ] bit shifts (#1062 / #1640 )
- [ ] if-then-else opcode for a conditional-move, but stack machine style (#1640)
- [ ] assert opcode (#1640)
- [ ] guarantees about integer constants, and maybe more 1 byte options.
- [ ] immediate varuint integers
- [ ] a `stringsplice` opcode like `substring`/`substring3` for injecting new bytes into a region (~ #1640)
- [ ] efficient msgpack-based byte string access, like LLVM's getelementptr
- [ ] accurate cost accounting and backward jumps (#1211)
- [ ] experimenting with different program limits (#1005)

I am very happy to implement most of these things, but I want to have a process in place for them to get in and testable beyond my own Algorand fork. I can wait a long time for it to be "live", but I don't want to wait a long time for it to be "eventually live".

Thanks!

**Comment by jeapostrophe** [comment]
I work around most of these issues today, but the Reach compiler has to produce much much larger TEAL programs than it otherwise would and it stresses the limits of TEAL quite a bit. For example, consider `stringsplice`

Here's the expected behavior:
```teal
bytes "0123456789"
bytes "aaaa"
stringsplice 3
bytes "012aaaa789"
=
```

If you don't have this op-code then you need to do something like:
```teal
...original...
// stack: [ bytes ]
dup
// stack: [ bytes, bytes ]
substring 0 3
// stack: [ before, bytes ]
...new value...
concat
// stack: [ before', bytes ]
swap
// stack: [ bytes, before' ]
substring 3 len
// stack: [ after, before' ]
swap
// stack: [ before', after ]
concat
// stack: [ bytes' ]
```

Except that actually, there is no `swap`, so you have to implement `swap` as `store 0 ; store 1; load 0; load 1` and pin those two slots always to being able to do a `swap`.

Also, you may not know `len` or at least it may be larger than `256`, so you may need to include it dynamically and use `substring3` to get the tail of the byte object.

This is very painful and inhibits large programs compiling to TEAL.

**Comment by jeapostrophe** [comment]
Here's what I mean by something like `getelementptr`:

I currently generate code like this:
```
  arg 9
  substring 72 144
  substring 64 72
  arg 9
  substring 0 72
  substring 64 72
  +
```

This takes the tenth argument (which is a struct with two fields of 72 bytes each; each field is a 9 int array). This code is basically `o.x[8] + o.y[8]`, but as you can see it is quite verbose. Even if I had a `swap` instruction, I could get rid of one `arg 9` and I could see if `dup/swap` would be better.

If I could have anything, then I'd define TEAL 3 (or TEAL 4 ;) ) as a really ISWIM-like language where you msgpack-encode the program and just provide a way to directly write a path like "gep(o, 0, 8)".

**Comment by jeapostrophe** [comment]
I just sent a PR for a few opcodes, #1640
