### ISSUE TITLE
HF Feature Networks

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3437]
## Objective
Create a network with characteristics similar to that of BetaNet for the Algorand developer community, internal engineering teams, and partners so that they can test, run experiments and explore an in-development feature.

## Value Add 
- Increase Algorand community engagement
- Shorten feedback loop to increase learning (feature usage patterns, user feedback)
- Early bug/error detection
- Transparency 

## Stakeholders
- Internal Eng
- External Developers 
- DevRel 

#### Description: Anyone can access a FeatureNet through the Algorand developer portal. They should have access to the following:

- [X] Ability to create and update job
- [ ] Create an update job with dropdown (list existing created network) 
- [X] Ability to delete job
- [ ] Automate Dispenser (create in an EKS cluster)
- [ ] Load generator ping-pong (create in an EKS cluster)
- [ ] multi-architecture support (arm32, arm64, darwin)
- [X] update.sh support (as long as the binary is placed in s3, the script should just fetch it) 
- [ ] Capturing network perf metrics and usage (Option1: ElasticSearch w/ Kibana and/or Datadog, Option 2: Prometheus w/ Grafana) 
- [ ] Design Indexer support
- [ ] Have a way for users to report bugs (github issue submission template that can be correlated to the appropriate FeatureNetwork) 
- [ ] Indexer support (Stretch goal, depending on size to implement)

#### Cross Team Dependencies: Who are we depending on? Who will be relying on us? 
Dev portal development team (Stakeholder: Ian Cross)
- [ ] Create page for FeatureNets (https://developer.algorand.org/get-details/algorand-networks/featurenet/ --> doesn't exist yet) 
- [ ] Connect page to jenkins for pushing binaries and FeatureNetwork details
- [ ] Lamprey will work figuring out how we can build amd64 support

#### Testing: 
- [ ] Test pushing binaries from jenkins to dev (check all architectures) (and check that when deleted and updated it is reflected on the webpage) 
- [ ] Test downloading binaries
- [ ] Test that we can connect to the network with all HW architectures
- [ ] Test reporting bugs 
- [ ] Test monitoring and behavioral insight on FeatureNet
- [ ] Test to confirm the FeatureNet is working (blocks being produced) 
- [ ] Test that update.sh (shell script that calls updater.sh) and updater.sh (does the fetching from s3 bucket) scripts are tested and FeatureNets are updated 

#### Exit criteria 
- Binaries can be pulled from Algorand developer portal and accounts can be created with enough to begin testing and using new features.
- Document how engineering (internal) can quickly launch a node that's connected to the appropriate FeatureNetwork
