### ISSUE TITLE
Betanet Transaction Sync Deployment

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#3767]
## Current BetaNet infrastructure 
5 non-participating instances each connected to a relay (R1 to R5) and 4 participating nodes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

## Required BetaNet Infrastructure
1. Create 4 relays in separate geo-zones and add them to the SRV record (R6 to R9)
2. Create 5 non-participating instances (same config as R5)
3. Create 2 nodes on each non-participating instance


## Phase 1: Before Transaction sync deployment
**Task** 
- [ ] Create new BetaNet Infrastructure

**Data points to collect**
AWS network bandwidth monitoring tool will be used to capture bandwidth on relays R6-R9
Measurement 1: bandwidth on relays R6-R9
Measurement 2: bandwidth of nodes created on R6-R9

**Acceptance criteria for the new BetaNet Infrastructure**
- Check TPS and ensure that this is unchanging
- After running the network for a day, the memory utilization should be consistent across R5 and R6-R9

## Phase 2: Immediately before Transaction Sync Deployment
**Task** 
- [ ] Update the config.json file on R1 - R5 to disable transaction sync 
- [ ] Update binaries on R1 - R5 and the participation nodes attached to R1 - R5
- [ ] Note: transaction sync is disabled

**Data points to collect** 
AWS network bandwidth monitoring tool will be used to capture bandwidth on relays R6-R9

- measure bandwidth on R6 - R9 
- measure bandwidth on the new nodes 
- The TPS measured should remain roughly constant

**Acceptance criteria** 
Compare bandwidth measurement and make sure they are within +/- 20%
Compare bandwidth of R1 - R9 while transaction sync is enabled on R1-R5 vs. bandwidth of R1 - R9 while transaction sync is DISABLED on R1-R5 
compare bandwidth on new nodes while transaction sync is enabled on R1-R5 vs. bandwidth on the new nodes while transaction sync is DISABLED on R1-R5 

## Phase 3: Transaction sync deployment
**Task** 
- [ ] During deployment, we are to upgrade on R1 - R5 and participation nodes gradually. Make sure transaction sync is disabled before restarting the nodes. Update the config.json on the relays and nodes so that the transaction sync is enabled 
- [ ] Upgrade one host per day 
- [ ] Update NetworkProtocol
Note: transaction sync is enabled

**Datapoints to collect**
- Collect bandwidth of relays R6 - R9 
- Collect bandwidth of newly added nodes 

**Acceptance criteria**
- Confirm that transactions aren't getting lost i.e. TPS should be consistent 
- Compare bandwidth of R6-R9 while transaction sync is deployed and enabled on R1-R5 VS bandwidth of R6-R9 while transaction sync is enabled on R1-R5 but NOT deployed on all nodes
- Compare bandwidth of all newly added nodes VS bandwidth of R6-R9 while transaction sync is enabled on R1-R5 but NOT deployed on all nodes

## Phase 4: Teardown new instances 
- [ ] Remove R6-R9 from SRV
- [ ] Remove R6-R9 instance
- [ ] Remove newly added nodes

https://docs.google.com/document/d/1Wkyjf5CUnvfmTg4tZVP6hRoZ-T1nyU21i1co_Iguyng/edit#
