### ISSUE TITLE
M1 Support: automation

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#3813]
This issue can be broken down as needed:
- [x] algod continuous integration / testing
- [x] algod release artifacts
- [x] indexer release artifacts

**Comment by onetechnical** [comment]
Probably also needs vendor review, unless we can get by with AWS instances.

**Comment by yaovi-a** [comment]
What about sandbox release artifacts?
